name: renamedock

services:
  renamedock:
    image: ghcr.io/2222221029/renamedock:latest
    container_name: renamedock
    restart: unless-stopped

    ports:
      - "2080:8080"

    environment:
      TZ: Asia/Shanghai
      NAS_ROOTS: /data
      CONFIG_DIR: /config
      # RENAMEDOCK_TOKEN: change-this-token

    volumes:
      # 将 /vol1 改成需要管理的飞牛 NAS 目录
      - /vol1:/data
      - ./config:/config

